# docker-compose.yml
version: "3"
services:
  omoponfhir-main:
    build:
      context: https://github.com/omoponfhir/omoponfhir-main.git#3be4f61674b5b62bffcf7b3a10c725ad20190f41
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment: # importantly specify the correct schema
      - JDBC_URL=jdbc:postgresql://omopv5fhir-pgsql:5432/postgres?currentSchema=omop_v5
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=i3lworks
    networks:
      omoponfhir:
  omopv5fhir-pgsql:
    build:
      context: https://github.com/omoponfhir/omopv5fhir-pgsql.git#0f21fcf5fb359b14f725d968b937d77a5a048117
    restart: unless-stopped
    ports:
      - "6543:5432"
    networks:
      omoponfhir:
networks:
  omoponfhir: